version: "3.8"

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/doctor_appointment_db
    depends_on:
      - mongo
    networks:
      - docs_api_network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: doctor_appointment_db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - docs_api_network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  docs_api_network:
    driver: bridge
